services:
  bot:
    build: .
    container_name: telegram-bot-transaksi
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./credentials.json:/app/credentials.json
    environment:
      - NODE_ENV=production 